config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'signup' , to: 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :ownerships, only: [:create, :destroy]
  resources :items , only: [:new , :show]

end

app/models/have.rb
class Have < Ownership
end

app/models/item.rb
class Item < ActiveRecord::Base
  serialize :raw_info , Hash

  has_many :ownerships  , foreign_key: "item_id" , dependent: :destroy
  has_many :users , through: :ownerships
  
  has_many :wants, foreign_key: "item_id", dependent: :destroy
  has_many :want_users, through: :wants, source: :user
  
  has_many :haves, foreign_key: "item_id", dependent: :destroy
  has_many :have_users, through: :haves, source: :user
  
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
  belongs_to :user, class_name: "User" #user
  belongs_to :item, class_name: "Item" #商品
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :following_relationships, class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  has_many :followed_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followed_users, through: :followed_relationships, source: :follower

  has_many :ownerships , foreign_key: "user_id", dependent: :destroy
  has_many :items ,through: :ownerships

  has_many :wants, class_name: "Want", foreign_key: "user_id", dependent: :destroy
  has_many :want_items, through: :wants, source: :item

  has_many :haves, class_name: "Have",foreign_key: "user_id" ,dependent: :destroy
  has_many :have_items, through: :haves, source: :item

  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    following_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following_users.include?(other_user)
  end

  ## TODO 実装
  def have(item)
    haves.create(user_id: item.id)
  end

  def unhave(item)
    haves.find_by(user_id: item.id).destroy
  end

  def have?(item)
    have_items.include?(item)
  end

  def want(item)
    wants.create(user_id: item.id)
  end

  def unwant(item)
    wants.find_by(user_id: item.id).destroy
  end

  def want?(item)
    want_items.include?(item)
  end
end

app/models/want.rb
class Want < Ownership
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user , except: [:show]
  before_action :set_item, only: [:show]

  def new
    if params[:q]
      response = Amazon::Ecs.item_search(params[:q] , 
                                  :search_index => 'All' , 
                                  :response_group => 'Medium' , 
                                  :country => 'jp')
      @amazon_items = response.items
    end
  end

  def show
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  before_action :logged_in_user

  def create
    if params[:asin]
      @item = Item.find_or_initialize_by(asin: params[:asin])
    else
      @item = Item.find(params[:item_id])
    end

    # itemsテーブルに存在しない場合はAmazonのデータを登録する。
    if @item.new_record?
      begin
        # TODO 商品情報の取得 Amazon::Ecs.item_lookupを用いてください
        response = Amazon::Ecs.item_lookup(params[:asin],
                                          :response_group => 'Medium' ,
                                          :country => 'jp')
      rescue Amazon::RequestError => e
        return render :js => "alert('#{e.message}')"
      end

      amazon_item       = response.items.first
      @item.title        = amazon_item.get('ItemAttributes/Title')
      @item.small_image  = amazon_item.get("SmallImage/URL")
      @item.medium_image = amazon_item.get("MediumImage/URL")
      @item.large_image  = amazon_item.get("LargeImage/URL")
      @item.detail_page_url = amazon_item.get("DetailPageURL")
      @item.raw_info        = amazon_item.get_hash
      @item.save!
    end

    # TODO ユーザにwant or haveを設定する
    # params[:type]の値ににHaveボタンが押された時にはの時は「Have」,
    # Wantボタンがされた時には「Want」が設定されています。
    if params[:type] == "Have"
      current_user.have(item.id)
    end
    
    if params[:type] == "Want"
      current_user.want(item.id)
    end

  end

  def destroy
    @item = Item.find(params[:item_id])

    # TODO 紐付けの解除。 
    # params[:type]の値ににHavedボタンが押された時にはの時は「Have」,
    # Wantedボタンがされた時には「Want」が設定されています。
    if params[:type] == "Have"
      current_user.unhave(item.id)
    end
    
    if params[:type] == "Want"
      current_user.unwant(item.id)
    end
    
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy
    relationship = current_user.following_relationships.find(params[:id])
    @user = relationship.followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to new_item_path if logged_in?
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "会員登録が完了しました"
    else
      render 'new'
    end
  end
  
  def show
    @items = @user.items
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @items = Item.all.order("updated_at DESC").limit(30)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/items/_action.html.erb
<div class="action">
  <% if current_user.want?(item) %>
    <%= render 'items/unwant', item: item %>
  <% else %>
    <%= render 'items/want', item: item %>
  <% end %> 

  <% if current_user.have? item %>
    <%= render 'items/unhave' , item: item %>
  <% else %>
    <%= render 'items/have' , item: item %>
  <% end %>

  <% unless current_page?(item) %>
    <%= link_to "詳細" , item , class: "btn btn-info btn-sm" %>
  <% end %>
</div>

app/views/items/_amazon_items.html.erb
<div class="container">
  <div class="container-inner inner-default clearfix">
    <% amazon_items.each do |item| %>
      <div class="item-box">
        <div class="image">
          <div class="img-wrap">
              <%= image_tag(item.get('LargeImage/URL')) %>
              <% if item.get('LargeImage/URL').nil? %>
                <%= image_tag('no-image.png') %>
              <% end %>
          </div>
        </div>
        <div class="detail">
          <p class="title">
            <%= item.get('ItemAttributes/Title') %>
          </p>
        </div>
        <div class="action clearfix">
          

          <%= link_to "" , ownerships_path(asin: item.get('ASIN') , type: "Want") ,
                      :class => "want-#{item.get('ASIN')} btn-want btn btn-danger btn-sm want",
                      :remote => true,
                      :method => :post %>
          <%= link_to "" , ownerships_path(asin: item.get('ASIN') , type: "Have") ,
                      :class => "have-#{item.get('ASIN')} btn-have btn btn-warning btn-sm have",
                      :remote => true,
                      :method => :post %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/_have.html.erb
<%= link_to "" , ownerships_path(item_id: item.id , type: "Have") ,
    :class => "have-#{item.id} btn-have btn btn-warning btn-sm have",
    :remote => true,
    :method => :post %>

app/views/items/_list.html.erb
<div class="container">
  <div class="container-inner inner-default clearfix">
    <% items.each do |item| %>
      <div class="item-box">
        <div class="image">
          <div class="img-wrap">
            <% if item.large_image.present? %>
              <%= image_tag(item.large_image , alt: item.title) %>
            <% else %>
              <%= image_tag("no-image.png" , alt: item.title) %>
            <% end %>
          </div>
        </div>
        <div class="detail">
          <p class="title">
            <%= item.title %>
          </p>
        </div>
        <%= render 'items/action' , item: item if logged_in? %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/_unhave.html.erb
<%= link_to "" , 
  ownership_path( current_user.haves.find_by(:item_id => item.id) , 
    item_id: item.id , type: "Have") ,
  :class => "have-#{item.id} btn-have btn btn-warning btn-sm haved",
  :remote => true,
  :method => :delete %> 

app/views/items/_unwant.html.erb
<%= link_to "" ,ownership_path(current_user.wants.find_by(:item_id => item.id) , 
      item_id: item.id , type: "Want") ,
    :class => "want-#{item.id} btn-want btn btn-danger btn-sm wanted",
    :remote => true,
    :method => :delete %>

app/views/items/_want.html.erb
<%= link_to "" , ownerships_path(item_id: item.id , type: "Want") ,
    :class => "want-#{item.id} btn-want btn btn-danger btn-sm want",
    :remote => true,
    :method => :post %>

app/views/items/new.html.erb
<div class="search">
  <%= form_tag new_item_path , method: :get do %>
    <%= text_field_tag :q , params[:q], placeholder: "キーワードを入力", required: true %>
    <%= submit_tag "アイテムを検索", name: nil , class: "btn btn-success", data: { disable_with: "検索中..."} %>
  <% end %>
</div>
<div class="search-result">
  <% if @amazon_items.present? %>
    <div class="alert alert-info">
      <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
      気になったアイテムが欲しければ「Want」持ってれば「Have」しましょう
    </div>
    <%= render 'amazon_items' , amazon_items: @amazon_items %>
  <% elsif params[:q].present? %>
    <div class="alert alert-danger">
      <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
      検索したアイテムはありません
    </div>
  <% end %>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="container-inner inner-sm clearfix">
    <div class="item-single-main">
      <div class="image">
        <div class="img-wrap">
          <% #TODO 商品イメージ %>
          <%= image_tag("no-image.png" , alt: @item.title) %>
        </div>
      </div>
      <div class="title">
        <% #TODO 商品タイトル %>
        仮タイトル
      </div>
      <%= render 'action' , item: @item %>
    </div>
    <div class="item-single-side">
      <div class="side-box">
        <h4 class="side-box-title">Haveしたユーザー</h4>
        <div class="side-box-body">
          <% # TODO Haveしたユーザー一覧 %>

        </div>
      </div>
      <div class="side-box">
        <h4 class="side-box-title">Wantしたユーザー</h4>
        <div class="side-box-body">
          <% # TODO Wantしたユーザー一覧 %>
        </div>
      </div>
      <div class="text-center">
        <% #TODO 正しいリンク先に %>
        <%= link_to(image_tag("amazon-button.png", {alt: "Amazon詳細ページへ"}), '#') %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="copyright">© <%= Date.today.year %> MONOLIST.</div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-inner">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h1 class="logo">
            <%= link_to "MONOLIST", root_path, class: "navbar-brand" %>
          </h1>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% unless logged_in? %>
              <li><%= link_to "新規登録", signup_path %></li>
              <li><%= link_to "ログイン", login_path %></li>
            <% else %>
              <li>
                <%= link_to new_item_path do %>
                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                  アイテムを追加
                <% end %>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span class="gravatar">
                    <%= gravatar_for current_user , size: 20 %>
                  </span>
                  <%= current_user.name %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "プロフィール" , current_user  %>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li>
                    <%= link_to "ログアウト", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if content_for?(:head) %>
    <%= yield :head %>
  <% else %>
    <title>Monolist</title>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
</head>
<body>

<%= render partial: "layouts/header" %>
<%= yield %>
<%= render partial: "layouts/footer" %>

</body>
</html>

app/views/ownerships/create.js.erb
<% if params[:type] == "Have" %>
  $(".have-<%= item.id %>,.have-<%= @item.asin %>").replaceWith("<%= escape_javascript(render('items/unhave' , item: @item)) %>");
<% else %>
  $(".want-<%= @item.id %>,.want-<%= @item.asin %>").replaceWith("<%= escape_javascript(render('items/unwant' , item: @item)) %>");
<% end %>

$('.btn-have,.btn-want').removeAttr('disabled');

app/views/ownerships/destroy.js.erb
<% if params[:type] == "Have" %>
  $(".have-<%= @item.id %>").replaceWith("<%= escape_javascript(render('items/have' , item: @item)) %>");
<% else %>
  $(".want-<%= @item.id %>").replaceWith("<%= escape_javascript(render('items/want' , item: @item)) %>");
<% end %>

$('.btn-have,.btn-want').removeAttr('disabled');

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followed_users.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followed_users.count %>');

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <button type="submit" class="btn btn-success btn-round">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Follow
  </button>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_profile.html.erb
<div class="user-profile">
  <div class="icon">
    <%= gravatar_for user, size: 100 %>
  </div>
  <div class="name">
    <h1><%= user.name %><h1>
  </div>
  <div class="status">
    <ul>
      <li>
        <div class="status-label">FOLLOWING</div>
        <div class="status-value">
          <%= user.following_users.count %>
        </div>
      </li>
      <li>
        <div class="status-label">FOLLOWERS</div>
        <div id="followers" class="status-value">
          <%= user.followed_users.count %>
        </div>
      </li>
      <li>
        <div class="status-label">WANT</div>
        <div id="want_count" class="status-value">
          789
        </div>
      </li>
      <li>
        <div class="status-label">HAVE</div>
        <div id="have_count" class="status-value">
          123
        </div>
      </li>
    </ul>

    <%= render 'follow_form' if logged_in? && @user != current_user %>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <button type class="btn btn-info btn-round">
      <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
      Following
    </button>
<% end %>

app/views/users/new.html.erb
<div class="box">
  <h2 class="box-title">会員登録</h2>
  <div class="box-inner">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.text_field :name, class: "form-control", placeholder: "お名前" %>
      </div>
      <div class="form-group">
        <%= f.text_field :email, class: "form-control", placeholder: "メールアドレス" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, class: "form-control", placeholder: "パスワード" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "パスワード（確認）" %>
      </div>
      <div class="submit-group">
        <%= f.submit "登録する", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'profile' , user: @user %>


<%= render 'items/list' , items: @items %>

app/views/welcome/index.html.erb
<div class="cover">
  <div class="cover-inner">
    <div class="cover-contents">
      <h1>素敵なモノと出会う場所</h1>
      <%= link_to 'モノリストを始める' , login_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>

<%= render 'items/list' , items: @items %>